apiVersion: v1
data:
  host: d3d0YmFtLmNidXVrczI4Z3VwZi5ldS1jZW50cmFsLTEucmRzLmFtYXpvbmF3cy5jb20=
  username: d3d0YmFt
  password: ZXp5ZWtOWTc=
kind: Secret
metadata:
  creationTimestamp: null
  name: mysql
